
import type { LessonItem } from "@/components/seminario/LessonCalendar";

export type LessonMeta = {
  slug: string;
  title: string;
  subtitle: string;
  date?: string;
  day?: "ter" | "qua" | "qui" | "sex";
};

export const allLessonMetas: LessonMeta[] = [
  {
    slug: "aula-1-nova-702-studying-the-messages",
    title: "Estudar as mensagens dos servos do Senhor",
    subtitle: "Tornar as palavras dos líderes da Igreja parte de seu aprendizado do evangelho",
    date: "2026-02-19",
    day: "qui",
  },
  {
    slug: "aula-2-nova-704-hope-of-israel",
    title: "“Juventude da promessa”",
    subtitle: "Estudar os ensinamentos dos líderes da Igreja",
    date: "2026-02-20",
    day: "sex",
  },
  {
    slug: "aula-3-nova-091-092-genesis-15-19",
    title: "E fez o Senhor (…) como tinha falado",
    subtitle: "Gênesis 15–18; 21 e Gênesis 19: confiar nas promessas de Deus e evitar influências malignas",
    date: "2026-02-24",
    day: "ter",
  },
  {
    slug: "aula-4-nova-093-genesis-22",
    title: "À semelhança de Jesus Cristo",
    subtitle: "Gênesis 22: o amor do Pai Celestial e de Jesus Cristo",
    date: "2026-02-25",
    day: "qua",
  },
  {
    slug: "aula-5-nova-094-doctrinal-mastery-2",
    title: "Prática de domínio doutrinário 2",
    subtitle: "Entender a doutrina e adquirir conhecimento espiritual",
    date: "2026-02-26",
    day: "qui",
  },
  {
    slug: "aula-6-nova-703-template-teachings-of-church-leaders",
    title: "Estudar e aplicar os ensinamentos dos servos do Senhor",
    subtitle: "Como usar o modelo para aprender com as mensagens dos líderes da Igreja",
    date: "2026-02-27",
    day: "sex",
  },
  {
    slug: "aula-7-nova-611-strengthening-spiritual-foundation",
    title: "Fortalecer seu alicerce espiritual",
    subtitle: "Introdução ao domínio doutrinário",
    date: "2026-03-03",
    day: "ter",
  },
  {
    slug: "aula-8-nova-612-seeking-personal-revelation",
    title: "Buscar revelação pessoal para minhas perguntas",
    subtitle: "Entender como o Senhor fala com você",
    date: "2026-03-04",
    day: "qua",
  },
  {
    slug: "aula-9-nova-101-102-genesis-24-27",
    title: "A bênção do convênio do casamento e Jacó e Esaú",
    subtitle: "Gênesis 24–27: casamento eterno e priorizar bênçãos eternas",
    date: "2026-03-05",
    day: "qui",
  },
  {
    slug: "aula-10-nova-103-104-genesis-28-33",
    title: "Convênios com o Senhor e permitir que Deus prevaleça",
    subtitle: "Gênesis 28–33: convênios no templo e Jacó como Israel",
    date: "2026-03-06",
    day: "sex",
  },
  {
    slug: "aula-11-nova-111-genesis-37-41",
    title: "E o Senhor estava com José",
    subtitle: "Gênesis 37–41: permanecer fiel durante provações",
    date: "2026-03-10",
    day: "ter",
  },
  {
    slug: "aula-12-nova-112-genesis-39",
    title: "Como vencer a tentação",
    subtitle: "Gênesis 39: José e a lei da castidade",
    date: "2026-03-11",
    day: "qua",
  },
  {
    slug: "aula-13-nova-613-acting-in-faith",
    title: "Agir com fé para encontrar respostas",
    subtitle: "Domínio doutrinário: primeiro princípio — agir com fé",
    date: "2026-03-12",
    day: "qui",
  },
  {
    slug: "aula-14-nova-614-examining-gospel-topics",
    title: "Examinar tópicos e perguntas do evangelho com uma perspectiva eterna",
    subtitle: "Domínio doutrinário: segundo princípio — perspectiva eterna",
    date: "2026-03-13",
    day: "sex",
  },
  {
    slug: "aula-15-nova-121-genesis-42-45",
    title: "Eu sou José, vosso irmão",
    subtitle: "Gênesis 42–45: perdoar como o Salvador",
    date: "2026-03-17",
    day: "ter",
  },
  {
    slug: "aula-16-nova-122-jst-genesis-50",
    title: "O Senhor meu Deus suscitará um vidente",
    subtitle: "Tradução de Joseph Smith, Gênesis 50: Joseph Smith profetizado",
    date: "2026-03-18",
    day: "qua",
  },
  {
    slug: "aula-17-nova-123-assess-your-learning-2",
    title: "Avalie seu aprendizado 2",
    subtitle: "Gênesis 12–50 e Abraão 1–2: avaliar crescimento espiritual",
    date: "2026-03-19",
    day: "qui",
  },
  {
    slug: "aula-18-nova-615-turning-to-divinely-appointed-sources",
    title: "Voltar-se para fontes divinamente atribuídas",
    subtitle: "Domínio doutrinário: terceiro princípio — fontes divinas",
    date: "2026-03-20",
    day: "sex",
  },
  {
    slug: "aula-19-nova-131-132-exodus-1-2-4",
    title: "Honrar a Deus e ouvir os profetas",
    subtitle: "Êxodo 1 (Sifrá e Puá) e Êxodo 2–4 (Moisés)",
    date: "2026-03-24",
    day: "ter",
  },
  {
    slug: "aula-20-nova-132-exodus-2-4",
    title: "Eu serei com a tua boca",
    subtitle: "O Senhor fala através de Seus profetas",
    date: "2026-03-25",
    day: "qua",
  },
  {
    slug: "aula-21-nova-621-focusing-on-the-savior",
    title: "Concentrar-se em Jesus Cristo nas escrituras",
    subtitle: "Técnicas de estudo das escrituras: símbolos e ações do Salvador",
    date: "2026-03-26",
    day: "qui",
  },
  {
    slug: "aula-22-061-moses-7",
    title: "Moisés 7:1–21",
    subtitle: "“O Senhor chamou Seu povo Sião”",
    date: "2026-03-27",
    day: "sex",
  },
  {
    slug: "aula-23-nova-701-preparing-for-general-conference",
    title: "Preparação para a conferência geral",
    subtitle: "Ouvir as palavras do Salvador na conferência geral",
    date: "2026-03-31",
    day: "ter",
  },
  {
    slug: "aula-24-nova-711-easter",
    title: "Páscoa",
    subtitle: "Esperança e paz por meio do Salvador e de Sua Expiação",
    date: "2026-04-01",
    day: "qua",
  },
  {
    slug: "aula-25-nova-come-follow-me-easter",
    title: "“[Ele] tragará a morte na vitória”",
    subtitle: "Páscoa: profetas antigos e atuais testificam do Salvador",
    date: "2026-04-02",
    day: "qui",
  },
  {
    slug: "aula-26-nova-141-exodus-7-11",
    title: "Reconhecer o poder do Senhor",
    subtitle: "Êxodo 7–11: o Senhor é mais poderoso que qualquer coisa",
    date: "2026-04-07",
    day: "ter",
  },
  {
    slug: "aula-27-nova-142-143-exodus-12-13",
    title: "A Páscoa do Senhor e o sacramento",
    subtitle: "Lembrar-se do Salvador sempre",
    date: "2026-04-08",
    day: "qua",
  },
  {
    slug: "aula-28-nova-144-doctrinal-mastery-practice-3",
    title: "Prática de domínio doutrinário 3",
    subtitle: "Memorização e aquisição de conhecimento espiritual",
    date: "2026-04-09",
    day: "qui",
  },
  {
    slug: "aula-29-nova-622-finding-gospel-truths",
    title: "Encontrar as verdades do evangelho nas escrituras",
    subtitle: "Aprender a identificar doutrina e princípios",
    date: "2026-04-10",
    day: "sex",
  },
  {
    slug: "aula-30-nova-151-152-exodus-14-18",
    title: "“Não temais” e identificar as verdades de Deus",
    subtitle: "Concentrar-se em Jesus Cristo e encontrar verdades nas escrituras",
    date: "2026-04-14",
    day: "ter",
  },
  {
    slug: "aula-31-nova-153-exodus-16",
    title: "O pão de cada dia",
    subtitle: "Confiar no Senhor todos os dias",
    date: "2026-04-15",
    day: "qua",
  },
  {
    slug: "aula-32-nova-623-annotating-scriptures",
    title: "Anotações das escrituras",
    subtitle: "Marcar, escrever notas e relacionar as escrituras",
    date: "2026-04-16",
    day: "qui",
  },
  {
    slug: "aula-33-nova-624-actions-that-invite-holy-ghost",
    title: "Ações que convidam o Espírito Santo ao estudo das escrituras",
    subtitle: "Criar um ambiente para o Espírito ensinar",
    date: "2026-04-17",
    day: "sex",
  },
  {
    slug: "aula-34-nova-161-162-exodus-19-20",
    title: "“Minha propriedade peculiar” e os primeiros quatro mandamentos",
    subtitle: "Relacionamento por convênio com Deus e amar a Deus acima de tudo",
    date: "2026-04-22",
    day: "qua",
  },
  {
    slug: "aula-35-nova-163-164-exodus-20-12-17-24-32-34",
    title: "Amar o próximo e a justiça, misericórdia e longanimidade do Senhor",
    subtitle: "Os últimos seis mandamentos e o caráter do Salvador",
    date: "2026-04-23",
    day: "qui",
  },
  {
    slug: "aula-36-nova-164-exodus-24-31-34-repentance",
    title: "O poder do arrependimento e a misericórdia do Senhor",
    subtitle: "Voltar ao Senhor e receber Seu perdão",
    date: "2026-04-24",
    day: "sex",
  },
  {
    slug: "aula-37-nova-171-exodus-25-35-40-temple",
    title: "“A glória do Senhor encheu o tabernáculo”",
    subtitle: "O tabernáculo e os templos: santuários para o Senhor habitar entre nós",
    date: "2026-04-28",
    day: "ter",
  },
  {
    slug: "aula-38-nova-172-173-leviticus-sacrifice-and-atonement",
    title: "“Isso é à semelhança” e “Sacrificar-se pelo Senhor”",
    subtitle: "Os sacrifícios antigos, a Expiação de Jesus Cristo e o que podemos sacrificar hoje",
    date: "2026-04-29",
    day: "qua",
  },
  {
    slug: "aula-39-nova-174-assess-your-learning-3",
    title: "Avalie seu aprendizado 3: Êxodo e Levítico",
    subtitle: "Refletir sobre crescimento espiritual, confiar no Senhor e seguir os profetas",
    date: "2026-04-30",
    day: "qui",
  },
  {
    slug: "aula-40-nova-181-numbers-11-14-faith-over-fear",
    title: "Escolher a fé em vez do medo",
    subtitle: "Calebe, Josué e a terra prometida: confiar no Senhor",
    date: "2026-05-05",
    day: "ter",
  },
  {
    slug: "aula-41-nova-182-numbers-21-look-to-savior",
    title: "Buscar o Salvador com fé",
    subtitle: "As serpentes ardentes, a serpente de bronze e Jesus Cristo",
    date: "2026-05-06",
    day: "qua",
  },
  {
    slug: "aula-42-nova-651-building-emotional-strength",
    title: "Desenvolver resiliência emocional no Senhor",
    subtitle: "O Salvador pode nos ajudar a aumentar nossa resiliência emocional",
    date: "2026-05-07",
    day: "qui",
  },
  {
    slug: "aula-43-nova-652-caring-for-our-physical-body",
    title: "Cuidados com nosso corpo",
    subtitle: "Melhorar nossa saúde física e emocional",
    date: "2026-05-08",
    day: "sex",
  },
  {
    slug: "aula-44-nova-191-deuteronomy-6-1-6",
    title: "Amar a Deus de todo o coração",
    subtitle: "Deuteronômio 6:1–6: amar o Senhor e mostrar esse amor em nossa vida cotidiana",
    date: "2026-05-12",
    day: "ter",
  },
  {
    slug: "aula-45-nova-192-deuteronomy-15",
    title: "Lembrarás do Senhor teu Deus",
    subtitle: "Deuteronômio 6:6–25; 7:1–26; 8:1–20: lembrar de Deus em todas as circunstâncias",
    date: "2026-05-13",
    day: "qua",
  },
  {
    slug: "aula-46-nova-653-developing-healthy-thinking",
    title: "Desenvolver padrões de pensamento saudáveis",
    subtitle: "“Cuja mente está firme em ti”: concentrar-se em Jesus Cristo",
    date: "2026-05-14",
    day: "qui",
  },
  {
    slug: "aula-47-nova-654-managing-stress-and-anxiety",
    title: "Administrar o estresse e a ansiedade",
    subtitle: "Jesus Cristo pode nos ajudar a controlar o estresse e a ansiedade",
    date: "2026-05-15",
    day: "sex",
  },
  {
    slug: "aula-48-nova-201-202-joshua-1-2-4",
    title: "Josué 1–4",
    subtitle: "O Senhor não nos deixará nem vai nos desamparar; exercer fé em Jesus Cristo",
    date: "2026-05-19",
    day: "ter",
  },
  {
    slug: "aula-49-nova-203-joshua-23-24",
    title: "Josué 23–24",
    subtitle: "“Escolhei hoje” a quem servireis",
    date: "2026-05-20",
    day: "qua",
  },
  {
    slug: "aula-50-nova-204-doctrinal-mastery-practice-4",
    title: "Prática de domínio doutrinário 4",
    subtitle: "Aplicar os princípios para adquirir conhecimento espiritual",
    date: "2026-05-21",
    day: "qui",
  },
  {
    slug: "aula-51-nova-655-coping-with-anger-and-depression",
    title: "Lidar com a tristeza e a depressão",
    subtitle: "Jesus Cristo carregará nosso pesar e nossa dor",
    date: "2026-05-22",
    day: "sex",
  },
  {
    slug: "aula-52-nova-211-212-judges-2-4-6-8",
    title: "Juízes 2–4; 6–8",
    subtitle: "Ciclo do orgulho; “Eu hei de ser contigo”",
    date: "2026-05-26",
    day: "ter",
  },
  {
    slug: "aula-53-nova-213-assess-your-learning-4",
    title: "Avalie seu aprendizado 4",
    subtitle: "Números–Juízes: refletir e avaliar o crescimento espiritual",
    date: "2026-05-27",
    day: "qua",
  },
  {
    slug: "aula-54-nova-656-resolving-feelings-of-anger",
    title: "Resolver sentimentos de raiva",
    subtitle: "Seguir o Salvador para reagir a sentimentos de raiva",
    date: "2026-05-28",
    day: "qui",
  },
  {
    slug: "aula-55-nova-711-easter",
    title: "Páscoa",
    subtitle: "O Salvador vive: esperança e paz por meio de Jesus Cristo",
    date: "2026-05-29",
    day: "sex",
  },
  {
    slug: "aula-56-nova-221-222-ruth-1-samuel-1",
    title: "Rute e 1 Samuel 1",
    subtitle: "Lição 68: Rute e Lição 69: 1 Samuel 1",
    date: "2026-06-02",
    day: "ter",
  },
  {
    slug: "aula-57-nova-223-1-samuel-3",
    title: "1 Samuel 3",
    subtitle: "“Fala, Senhor, porque o teu servo ouve”",
    date: "2026-06-03",
    day: "qua",
  },
  {
    slug: "aula-58-nova-657-developing-healthy-habits",
    title: "Desenvolver hábitos saudáveis",
    subtitle: "Jesus Cristo pode nos ajudar a mudar nossos hábitos",
    date: "2026-06-05",
    day: "sex",
  },
  {
    slug: "aula-59-nova-231-1-samuel-8",
    title: "1 Samuel 8",
    subtitle: "Israel deseja um rei",
    date: "2026-06-09",
    day: "ter",
  },
  {
    slug: "aula-60-nova-232-1-samuel-15",
    title: "1 Samuel 15",
    subtitle: "Esforçar-se para guardar todos os mandamentos de Deus",
    date: "2026-06-10",
    day: "qua",
  },
  {
    slug: "aula-61-nova-233-1-samuel-16",
    title: "1 Samuel 16",
    subtitle: "“O Senhor olha para o coração”",
    date: "2026-06-11",
    day: "qui",
  },
  {
    slug: "aula-62-nova-671-involving-the-lord",
    title: "Envolvendo o Senhor",
    subtitle: "Ele vai magnificar e fortalecer seus esforços",
    date: "2026-06-12",
    day: "sex",
  },
  {
    slug: "aula-63-nova-241-1-samuel-17",
    title: "1 Samuel 17",
    subtitle: "“O Senhor que me livrou da pata do leão e da pata do urso, ele me livrará da mão deste filisteu”",
    date: "2026-06-16",
    day: "ter",
  },
  {
    slug: "aula-64-nova-242-1-samuel-25",
    title: "1 Samuel 25",
    subtitle: "O Salvador nos ajuda a perdoar",
    date: "2026-06-17",
    day: "qua",
  },
  {
    slug: "aula-65-nova-243-doctrinal-mastery-practice-5",
    title: "Prática de domínio doutrinário 5",
    subtitle: "Memorizar passagens e aplicar os princípios para adquirir conhecimento espiritual",
    date: "2026-06-18",
    day: "qui",
  },
  {
    slug: "aula-66-nova-672-taking-responsibility-for-your-learning",
    title: "Assumir a responsabilidade por seu aprendizado",
    subtitle: "Evitar desculpas e tomar iniciativa na educação",
    date: "2026-06-19",
    day: "sex",
  },
  {
    slug: "aula-67-nova-251-2-samuel-11-12",
    title: "2 Samuel 11–12",
    subtitle: "Não podemos esconder nossos pecados do Senhor",
    date: "2026-06-23",
    day: "ter",
  },
  {
    slug: "aula-68-nova-252-1-kings-3-253-1-kings-6-9",
    title: "1 Reis 3; 6–9",
    subtitle: "O Senhor nos abençoa para realizarmos Sua obra",
    date: "2026-06-24",
    day: "qua",
  },
  {
    slug: "aula-69-nova-254-assess-your-learning-5",
    title: "Avalie seu aprendizado 5",
    subtitle: "Rute–1 Reis 11",
    date: "2026-06-25",
    day: "qui",
  },
  {
    slug: "aula-70-nova-673-organizing-tasks-and-priorities",
    title: "Organizar tarefas e prioridades",
    subtitle: "O exemplo do Salvador pode nos ajudar a colocar nossa vida em ordem",
    date: "2026-06-26",
    day: "sex",
  },
  {
    slug: "aula-71-nova-703-template-teachings-of-church-leaders",
    title: "Modelo para ensinar mensagens dos líderes da Igreja",
    subtitle: "Estudar e aplicar os ensinamentos dos servos do Senhor",
    date: "2026-06-30",
    day: "ter",
  },
  {
    slug: "aula-72-nova-261-1-kings-17",
    title: "1 Reis 17",
    subtitle: "“E foi ela, e fez conforme a palavra de Elias”",
    date: "2026-07-01",
    day: "qua",
  },
  {
    slug: "aula-73-nova-262-1-kings-18",
    title: "1 Reis 18",
    subtitle: "Escolher seguir o Senhor",
    date: "2026-07-02",
    day: "qui",
  },
  {
    slug: "aula-74-nova-262-1-kings-18",
    title: "1 Reis 18",
    subtitle: "Escolher seguir o Senhor",
    date: "2026-07-03",
    day: "sex",
  },
];

export function getLessonMetaBySlug(slug: string): LessonMeta | null {
  return allLessonMetas.find((l) => l.slug === slug) ?? null;
}

