export type LessonMeta = {
  slug: string;
  title: string;
  subtitle: string;
  date?: string;
  day?: "ter" | "qua" | "qui" | "sex";
};

export const allLessonMetas: LessonMeta[] = [
  {
    slug: "aula-1-nova-702-studying-the-messages",
    title: "Estudar as mensagens dos servos do Senhor",
    subtitle: "Tornar as palavras dos líderes da Igreja parte de seu aprendizado do evangelho",
    date: "2026-02-19",
    day: "qui",
  },
  {
    slug: "aula-2-nova-704-hope-of-israel",
    title: "“Juventude da promessa”",
    subtitle: "Estudar os ensinamentos dos líderes da Igreja",
    date: "2026-02-20",
    day: "sex",
  },
  {
    slug: "aula-3-nova-091-092-genesis-15-19",
    title: "E fez o Senhor (…) como tinha falado",
    subtitle: "Gênesis 15–18; 21 e Gênesis 19: confiar nas promessas de Deus e evitar influências malignas",
    date: "2026-02-24",
    day: "ter",
  },
  {
    slug: "aula-4-nova-093-genesis-22",
    title: "À semelhança de Jesus Cristo",
    subtitle: "Gênesis 22: o amor do Pai Celestial e de Jesus Cristo",
    date: "2026-02-25",
    day: "qua",
  },
  {
    slug: "aula-5-nova-094-doctrinal-mastery-2",
    title: "Prática de domínio doutrinário 2",
    subtitle: "Entender a doutrina e adquirir conhecimento espiritual",
    date: "2026-02-26",
    day: "qui",
  },
  {
    slug: "aula-6-nova-703-template-teachings-of-church-leaders",
    title: "Estudar e aplicar os ensinamentos dos servos do Senhor",
    subtitle: "Como usar o modelo para aprender com as mensagens dos líderes da Igreja",
    date: "2026-02-27",
    day: "sex",
  },
  {
    slug: "aula-7-nova-611-strengthening-spiritual-foundation",
    title: "Fortalecer seu alicerce espiritual",
    subtitle: "Introdução ao domínio doutrinário",
    date: "2026-03-03",
    day: "ter",
  },
  {
    slug: "aula-8-nova-612-seeking-personal-revelation",
    title: "Buscar revelação pessoal para minhas perguntas",
    subtitle: "Entender como o Senhor fala com você",
    date: "2026-03-04",
    day: "qua",
  },
  {
    slug: "aula-9-nova-101-102-genesis-24-27",
    title: "A bênção do convênio do casamento e Jacó e Esaú",
    subtitle: "Gênesis 24–27: casamento eterno e priorizar bênçãos eternas",
    date: "2026-03-05",
    day: "qui",
  },
  {
    slug: "aula-10-nova-103-104-genesis-28-33",
    title: "Convênios com o Senhor e permitir que Deus prevaleça",
    subtitle: "Gênesis 28–33: convênios no templo e Jacó como Israel",
    date: "2026-03-06",
    day: "sex",
  },
  {
    slug: "aula-11-nova-111-genesis-37-41",
    title: "E o Senhor estava com José",
    subtitle: "Gênesis 37–41: permanecer fiel durante provações",
    date: "2026-03-10",
    day: "ter",
  },
  {
    slug: "aula-12-nova-112-genesis-39",
    title: "Como vencer a tentação",
    subtitle: "Gênesis 39: José e a lei da castidade",
    date: "2026-03-11",
    day: "qua",
  },
  {
    slug: "aula-13-nova-613-acting-in-faith",
    title: "Agir com fé para encontrar respostas",
    subtitle: "Domínio doutrinário: primeiro princípio — agir com fé",
    date: "2026-03-12",
    day: "qui",
  },
  {
    slug: "aula-14-nova-614-examining-gospel-topics",
    title: "Examinar tópicos e perguntas do evangelho com uma perspectiva eterna",
    subtitle: "Domínio doutrinário: segundo princípio — perspectiva eterna",
    date: "2026-03-13",
    day: "sex",
  },
  {
    slug: "aula-15-nova-121-genesis-42-45",
    title: "Eu sou José, vosso irmão",
    subtitle: "Gênesis 42–45: perdoar como o Salvador",
    date: "2026-03-17",
    day: "ter",
  },
  {
    slug: "aula-16-nova-122-jst-genesis-50",
    title: "O Senhor meu Deus suscitará um vidente",
    subtitle: "Tradução de Joseph Smith, Gênesis 50: Joseph Smith profetizado",
    date: "2026-03-18",
    day: "qua",
  },
  {
    slug: "aula-17-nova-123-assess-your-learning-2",
    title: "Avalie seu aprendizado 2",
    subtitle: "Gênesis 12–50 e Abraão 1–2: avaliar crescimento espiritual",
    date: "2026-03-19",
    day: "qui",
  },
  {
    slug: "aula-18-nova-615-turning-to-divinely-appointed-sources",
    title: "Voltar-se para fontes divinamente atribuídas",
    subtitle: "Domínio doutrinário: terceiro princípio — fontes divinas",
    date: "2026-03-20",
    day: "sex",
  },
  {
    slug: "aula-19-nova-131-132-exodus-1-2-4",
    title: "Honrar a Deus e ouvir os profetas",
    subtitle: "Êxodo 1 (Sifrá e Puá) e Êxodo 2–4 (Moisés)",
    date: "2026-03-24",
    day: "ter",
  },
  {
    slug: "aula-20-053-doctrinal-mastery",
    title: "Prática de Domínio Doutrinário 1",
    subtitle: "Memorizar e aplicar conhecimento espiritual",
    date: "2026-03-25",
    day: "qua",
  },
  {
    slug: "aula-21-060-overview",
    title: "Moisés 7",
    subtitle: "Visão geral: Sião, lágrimas de Deus e esperança",
    date: "2026-03-26",
    day: "qui",
  },
  {
    slug: "aula-22-061-moses-7",
    title: "Moisés 7:1–21",
    subtitle: "“O Senhor chamou Seu povo Sião”",
    date: "2026-03-27",
    day: "sex",
  },
  {
    slug: "aula-23-062-moses-7",
    title: "Moisés 7:22–47",
    subtitle: "A visão de Enoque",
    date: "2026-03-31",
    day: "ter",
  },
  {
    slug: "aula-24-063-moses-7",
    title: "Moisés 7:53–69",
    subtitle: "O Rei de Sião preservará Seu povo",
    date: "2026-04-01",
    day: "qua",
  },
  {
    slug: "aula-25-070-overview",
    title: "Gênesis 6–11; Moisés 8",
    subtitle: "Visão geral: Noé, obediência e livramento",
    date: "2026-04-02",
    day: "qui",
  },
  {
    slug: "aula-26-071-moses-8",
    title: "Moisés 8",
    subtitle: "Seguir o Salvador em um mundo iníquo",
    date: "2026-04-07",
    day: "ter",
  },
  {
    slug: "aula-27-072-genesis-6-8",
    title: "Gênesis 6–8",
    subtitle: "“Noé fez (…) tudo o que o Senhor lhe ordenara”",
    date: "2026-04-08",
    day: "qua",
  },
  {
    slug: "aula-28-073-assess-your-learning-1",
    title: "Avalie seu aprendizado 1",
    subtitle: "Moisés 1–Gênesis 11",
    date: "2026-04-09",
    day: "qui",
  },
  {
    slug: "aula-29-080-overview",
    title: "Gênesis 12–17; Abraão 1–2",
    subtitle: "Visão geral: o convênio abraâmico",
    date: "2026-04-10",
    day: "sex",
  },
  {
    slug: "aula-30-081-abraham-1",
    title: "Abraão 1",
    subtitle: "“Desejando (…) ser (…) seguidor da retidão”",
    date: "2026-04-14",
    day: "ter",
  },
  {
    slug: "aula-31-082-genesis-12-17",
    title: "Gênesis 12; 17",
    subtitle: "O convênio abraâmico",
    date: "2026-04-15",
    day: "qua",
  },
  {
    slug: "aula-32-083-abraham-2",
    title: "Abraão 2:9–11",
    subtitle: "Nossas responsabilidades no convênio abraâmico",
    date: "2026-04-16",
    day: "qui",
  },
  {
    slug: "aula-33-090-overview",
    title: "Gênesis 18–23",
    subtitle: "Visão geral: promessas, escolhas e fé",
    date: "2026-04-17",
    day: "sex",
  },
  {
    slug: "aula-34-091-genesis-15-18-21",
    title: "Gênesis 15–18; 21",
    subtitle: "O Senhor cumpre Suas promessas",
    date: "2026-04-22",
    day: "qua",
  },
  {
    slug: "aula-35-092-genesis-19",
    title: "Gênesis 19",
    subtitle: "“Não olhes para trás de ti”",
    date: "2026-04-23",
    day: "qui",
  },
  {
    slug: "aula-36-093-genesis-22",
    title: "Gênesis 22",
    subtitle: "À semelhança de Jesus Cristo",
    date: "2026-04-24",
    day: "sex",
  },
  {
    slug: "aula-37-094-doctrinal-mastery",
    title: "Prática de Domínio Doutrinário 2",
    subtitle: "Entender a doutrina e adquirir conhecimento espiritual",
    date: "2026-04-28",
    day: "ter",
  },
  {
    slug: "aula-38-100-overview",
    title: "Gênesis 24–33",
    subtitle: "Visão geral: convênios, escolhas e reconciliação",
    date: "2026-04-29",
    day: "qua",
  },
  {
    slug: "aula-39-101-genesis-24",
    title: "Gênesis 24",
    subtitle: "A bênção do convênio do casamento",
    date: "2026-04-30",
    day: "qui",
  },
  {
    slug: "aula-40-102-genesis-25-27",
    title: "Gênesis 25–27",
    subtitle: "Jacó e Esaú: valorizar bênçãos eternas",
    date: "2026-05-05",
    day: "ter",
  },
  {
    slug: "aula-41-103-genesis-28",
    title: "Gênesis 28",
    subtitle: "Convênios com o Senhor",
    date: "2026-05-06",
    day: "qua",
  },
  {
    slug: "aula-42-104-genesis-29-33",
    title: "Gênesis 29–33",
    subtitle: "“Permita que Deus prevaleça”",
    date: "2026-05-07",
    day: "qui",
  },
  {
    slug: "aula-43-110-overview",
    title: "Gênesis 37–41",
    subtitle: "Visão geral: Deus pode usar provações para abençoar",
    date: "2026-05-08",
    day: "sex",
  },
  {
    slug: "aula-44-111-genesis-37-41",
    title: "Gênesis 37–41",
    subtitle: "“E o Senhor estava com José”",
    date: "2026-05-12",
    day: "ter",
  },
  {
    slug: "aula-78-193-deuteronomy-15",
    title: "Deuteronômio 15",
    subtitle: "“Abrirás de todo a tua mão”",
    date: "2026-05-13",
    day: "qua",
  },
  {
    slug: "aula-46-120-overview",
    title: "Gênesis 42–50",
    subtitle: "Visão geral: perdão, família e profecia",
    date: "2026-05-14",
    day: "qui",
  },
  {
    slug: "aula-47-121-genesis-42-45",
    title: "Gênesis 42–45",
    subtitle: "“Eu sou José, vosso irmão”",
    date: "2026-05-15",
    day: "sex",
  },
  {
    slug: "aula-48-122-jst-genesis-50",
    title: "TJS Gênesis 50",
    subtitle: "“O Senhor meu Deus suscitará um vidente”",
    date: "2026-05-19",
    day: "ter",
  },
  {
    slug: "aula-49-123-assess-your-learning-2",
    title: "Avalie seu aprendizado 2",
    subtitle: "Gênesis 12–50 e Abraão 1–2",
    date: "2026-05-20",
    day: "qua",
  },
  {
    slug: "aula-50-130-overview",
    title: "Êxodo 1–6",
    subtitle: "Visão geral: Deus ouve clamores e levanta libertadores",
    date: "2026-05-21",
    day: "qui",
  },
  {
    slug: "aula-51-131-exodus-1",
    title: "Êxodo 1",
    subtitle: "Honrar a Deus diante da oposição",
    date: "2026-05-22",
    day: "sex",
  },
  {
    slug: "aula-52-132-exodus-2-4",
    title: "Êxodo 2–4",
    subtitle: "“Eu serei com a tua boca”",
    date: "2026-05-26",
    day: "ter",
  },
  {
    slug: "aula-53-133-exodus-5-6",
    title: "Êxodo 5–6",
    subtitle: "Fazer a vontade do Senhor sem retorno imediato",
    date: "2026-05-27",
    day: "qua",
  },
  {
    slug: "aula-54-710-easter",
    title: "Páscoa",
    subtitle: "Olhar para Cristo e encontrar vida",
    date: "2026-05-28",
    day: "qui",
  },
  {
    slug: "aula-55-711-easter",
    title: "Páscoa",
    subtitle: "O Salvador vive: esperança para recomeçar",
    date: "2026-05-29",
    day: "sex",
  },
  {
    slug: "aula-56-nova-221-222-ruth-1-samuel-1",
    title: "Rute e 1 Samuel 1",
    subtitle: "Lição 68: Rute e Lição 69: 1 Samuel 1",
    date: "2026-06-02",
    day: "ter",
  },
  {
    slug: "aula-57-nova-223-1-samuel-3",
    title: "1 Samuel 3",
    subtitle: "“Fala, Senhor, porque o teu servo ouve”",
    date: "2026-06-03",
    day: "qua",
  },
  {
    slug: "aula-58-nova-657-developing-healthy-habits",
    title: "Desenvolver hábitos saudáveis",
    subtitle: "Jesus Cristo pode nos ajudar a mudar nossos hábitos",
    date: "2026-06-05",
    day: "sex",
  },
  {
    slug: "aula-59-nova-231-1-samuel-8",
    title: "1 Samuel 8",
    subtitle: "Israel deseja um rei",
    date: "2026-06-09",
    day: "ter",
  },
  {
    slug: "aula-60-nova-232-1-samuel-15",
    title: "1 Samuel 15",
    subtitle: "Esforçar-se para guardar todos os mandamentos de Deus",
    date: "2026-06-10",
    day: "qua",
  },
  {
    slug: "aula-61-nova-233-1-samuel-16",
    title: "1 Samuel 16",
    subtitle: "“O Senhor olha para o coração”",
    date: "2026-06-11",
    day: "qui",
  },
  {
    slug: "aula-62-151-exodus-14",
    title: "Êxodo 14",
    subtitle: "“Não temais; estai quietos”",
    date: "2026-06-12",
    day: "sex",
  },
  {
    slug: "aula-63-152-exodus-15-17",
    title: "Êxodo 15; 17",
    subtitle: "Identificar verdades de Deus nas escrituras",
    date: "2026-06-16",
    day: "ter",
  },
  {
    slug: "aula-64-nova-242-1-samuel-25",
    title: "1 Samuel 25",
    subtitle: "O Salvador nos ajuda a perdoar",
    date: "2026-06-17",
    day: "qua",
  },
  {
    slug: "aula-65-nova-243-doctrinal-mastery-practice-5",
    title: "Prática de domínio doutrinário 5",
    subtitle: "Memorizar passagens e aplicar os princípios para adquirir conhecimento espiritual",
    date: "2026-06-18",
    day: "qui",
  },
  {
    slug: "aula-66-nova-672-taking-responsibility-for-your-learning",
    title: "Assumir a responsabilidade por seu aprendizado",
    subtitle: "Evitar desculpas e tomar iniciativa na educação",
    date: "2026-06-19",
    day: "sex",
  },
  {
    slug: "aula-67-nova-251-2-samuel-11-12",
    title: "2 Samuel 11–12",
    subtitle: "Não podemos esconder nossos pecados do Senhor",
    date: "2026-06-23",
    day: "ter",
  },
  {
    slug: "aula-68-nova-252-1-kings-3-253-1-kings-6-9",
    title: "1 Reis 3; 6–9",
    subtitle: "O Senhor nos abençoa para realizarmos Sua obra",
    date: "2026-06-24",
    day: "qua",
  },
  {
    slug: "aula-69-nova-254-assess-your-learning-5",
    title: "Avalie seu aprendizado 5",
    subtitle: "Rute–1 Reis 11",
    date: "2026-06-25",
    day: "qui",
  },
  {
    slug: "aula-70-nova-673-organizing-tasks-and-priorities",
    title: "Organizar tarefas e prioridades",
    subtitle: "O exemplo do Salvador pode nos ajudar a colocar nossa vida em ordem",
    date: "2026-06-26",
    day: "sex",
  },
  {
    slug: "aula-71-nova-703-template-teachings-of-church-leaders",
    title: "Modelo para ensinar mensagens dos líderes da Igreja",
    subtitle: "Estudar e aplicar os ensinamentos dos servos do Senhor",
    date: "2026-06-30",
    day: "ter",
  },
  {
    slug: "aula-72-nova-261-1-kings-17",
    title: "1 Reis 17",
    subtitle: "“E foi ela, e fez conforme a palavra de Elias”",
    date: "2026-07-01",
    day: "qua",
  },
  {
    slug: "aula-73-nova-262-1-kings-18",
    title: "1 Reis 18",
    subtitle: "Escolher seguir o Senhor",
    date: "2026-07-02",
    day: "qui",
  },
  {
    slug: "aula-74-nova-262-1-kings-18",
    title: "1 Reis 18",
    subtitle: "Escolher seguir o Senhor",
    date: "2026-07-03",
    day: "sex",
  },
];

export function getLessonMetaBySlug(slug: string): LessonMeta | null {
  return allLessonMetas.find((l) => l.slug === slug) ?? null;
}
